games/urls.py
from django.conf.urls import url
from . import views

app_name = 'games'

urlpatterns = [
    # /games/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /games/register/
    url(r'register/$', views.UserFormView.as_view(), name='register'),


    # /games/all_games/
    url(r'all_games/$', views.AllGames.as_view(), name='all_games'),


    # /games/<console_id>/ #
    url(r'^(?P<pk>[0-9]+)$', views.ConsoleGames.as_view(), name='console_games'),

    # /games/console/add/ #
    url(r'console/add/$', views.ConsoleCreate.as_view(), name='console_add'),

    # /games/console/<pk>/ #
    url(r'console/(?P<pk>[0-9]+)/$', views.ConsoleUpdate.as_view(), name='console_update'),

    # /games/console/<pk>/delete #
    url(r'console/(?P<pk>[0-9]+)/delete/$', views.ConsoleDelete.as_view(), name='console_delete'),

    # /games/<game_id>/ #
    url(r'^(?P<pk>[0-9]+)/$', views.GameDetail.as_view(), name='game_detail'),

    # /games/game/add/ #
    url(r'game/add/$', views.GameCreate.as_view(), name='game_add'),

    # /games/console/<pk>/ #
    url(r'game/(?P<pk>[0-9]+)/$', views.GameUpdate.as_view(), name='game_update'),

    # /games/game/<pk>/delete #
    url(r'game/(?P<pk>[0-9]+)/delete/$', views.GameDelete.as_view(), name='game_delete'),

    # /games/<game_id>/completed/ #
    #url(r'^(?P<game_id>[0-9]+)/completed/$', views.completed, name='completed'),
]

website/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^games/', include('games.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/models.py
from django.db import models
from django.urls import reverse

class Console(models.Model):
    name = models.CharField(max_length=100)
    publisher = models.CharField(max_length=100)
    description = models.CharField(max_length=5000)
    image = models.FileField()

    def get_absolute_url(self):
        return reverse('games:console_games', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' - ' + self.publisher


class Game(models.Model):
    console = models.ForeignKey(Console, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    year = models.CharField(max_length=4)
    genre = models.CharField(max_length=35)
    description = models.CharField(max_length=5000)
    image = models.FileField()
    completed = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('games:game_detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.name + ' - ' + self.year

games/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

games/views.py
from .models import Console, Game
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from django.urls import reverse, reverse_lazy
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'games/index.html'
    context_object_name = 'all_consoles'

    def get_queryset(self):
        return Console.objects.all()


class AllGames(generic.ListView):
    template_name = 'games/all_games.html'
    context_object_name = 'all_games'

    def get_queryset(self):
        return Game.objects.all()


class ConsoleGames(generic.DetailView):
    model = Console
    template_name = 'games/console_games.html'


class ConsoleCreate(CreateView):
    model = Console
    fields = ['name', 'publisher', 'image', 'description']


class ConsoleUpdate(UpdateView):
    model = Console
    fields = ['name', 'publisher', 'image', 'description']


class ConsoleDelete(DeleteView):
    model = Console
    success_url = reverse_lazy('games:index')


class GameDetail(generic.DetailView):
    model = Game
    template_name = 'games/game_detail.html'


class GameCreate(CreateView):
    model = Game
    fields = ['name', 'console', 'year', 'genre', 'image', 'description']


class GameUpdate(UpdateView):
    model = Game
    fields = ['name', 'console', 'year', 'genre', 'image', 'description']


class GameDelete(DeleteView):
    model = Game
    success_url = reverse_lazy('games:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'games/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # normalised - for dates for example
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return user object if correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('games:index')

        return render(request, self.template_name, {'form': form})

#
# def index(request):
#     all_consoles = Console.objects.all()
#     return render(request, 'games/index.html', {'all_consoles': all_consoles})
#
#
# def console_games(request, console_id):
#     console = get_object_or_404(Console, id=console_id)
#     return render(request, 'games/console_games.html', {'console': console})
#
#
# def game_detail(request, game_id):
#     game = get_object_or_404(Game, id=game_id)
#     return render(request, 'games/game_detail.html', {'game': game})
#
#
# def completed(request, game_id):
#     game = get_object_or_404(Game, id=game_id)
#     game.completed = not game.completed
#     game.save()
#     return render(request, 'games/game_detail.html', {'game': game})
#
#

games/templates/games/all_games.html
{% extends 'games/base.html' %}


{% block body %}

    {% if all_games %}


    <div class="container">
      <div class="row">

          {% for game in all_games %}

            {% include 'games/game_thumb.html' %}

          {% endfor %}
      </div>

    </div>

    {% else %}

    <h3>No games to list...</h3>

    {% endif %}



{% endblock %}

games/templates/games/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'games/style.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>{% block title %}Games{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'games:index' %}">G4m3rr</a>
        </div>

        <!-- ITEMS -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li id="nav-consoles" class="">
                    <a href="{% url 'games:index' %}">
                        <span class="glyphicon glyphicon-hdd" aria-hidden="true"></span>&nbsp; Consoles
                    </a>
                </li>
                <li id="nav-games"  class="">
                    <a href="{% url 'games:all_games' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Games
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="" />
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                    <li id="nav-add-console" class="">
                        <a href="{% url 'games:console_add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Console
                        </a>
                    </li>
                    <li id="nav-add-game" class="">
                        <a href="{% url 'games:game_add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Game
                        </a>
                    </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}


</body>
</html>

<script>

    $('a[href="' + this.location.pathname + '"]').parents('li,ul').addClass('active');

</script>

games/templates/games/console_form.html
{% extends 'games/base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create New Console</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'games/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>


{% endblock %}

games/templates/games/console_games.html
{% extends 'games/base.html' %}

{% block body %}


    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}

    <div class="jumbotron">
      <div class="container">
          <div class="col-md-8">
            <h1>{{ console.name }}</h1>
            <h3>{{ console.publisher }}</h3>
              <p>{{ console.description }}</p>
          </div>
          <div class="col-md-4">
            <img class="game-thumb" src="{{ console.image.url }}" />
          </div>
      </div>
    </div>

    {% if console.game_set.count > 0 %}
    <div class="container">
      <div class="row">

        {% for game in console.game_set.all %}

            {% include 'games/game_thumb.html' %}

        {% endfor %}
      </div>

    </div>

    {% else %}

    <h3>No games to list...</h3>

    {% endif %}



{% endblock %}

games/templates/games/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

games/templates/games/game_detail.html
{% extends 'games/base.html' %}

{% block body %}

    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}

    <div class="jumbotron">
          <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-12">
                                <h1>{{ game.name }}</h1>
                                <h3>{{ game.year }} {{ game.genre }}</h3>
                            </div>
                            <div class="col-md-12">
                                <p>{{ game.description }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <img class="game-thumb" src="{{ game.image.url }}" />

                    </div>

                </div>

      </div>
    </div>

{% endblock %}

games/templates/games/game_form.html
{% extends 'games/base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create New Game</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'games/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>


{% endblock %}

games/templates/games/game_thumb.html
<div class="col-xs-6 col-sm-6 col-md-3 container">
<div class="border-shadow">

            <div class="row">

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <a href="{% url 'games:game_detail' game.id %}">
                            <img class="game-thumb" src="{{ game.image.url }}" />
                        </a>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8 game-thumb-wrap">
                        {{ game.name }}
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 game-thumb-wrap">
                        {{ game.year }}
                    </div>
                    <div class="col-xs-5 col-sm-5 col-md-5 game-thumb-wrap">
                        {{ game.genre }}
                    </div>

                    <div class="col-xs-2 col-sm-2 col-md-2">
                        <!-- Update Game -->
                            <form action="{% url 'games:game_update' game.id %}" method="get" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="game_id" value="{{ game.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                            </form>
                    </div>
                    <div class="col-xs-2 col-sm-2 col-md-2">
                        <!-- Delete Game -->
                            <form action="{% url 'games:game_delete' game.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="game_id" value="{{ game.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                    </div>

                </div>
</div>
        </div>

games/templates/games/index.html
{% extends 'games/base.html' %}


{% block body %}

    {% if all_consoles %}


    <div class="container">
      <div class="row">

          {% for console in all_consoles %}

        <div class="col-xs-12 col-sm-6 col-md-3">
            <a href="{% url 'games:console_games' console.id %}">
<div class="border-shadow console-thumb">
                <div class="row">

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <img class="game-thumb" src="{{ console.image.url }}" />
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">

                        <div class="row">

                            <div class="col-xs-12 col-sm-12 col-md-12"><h2>{{ console.name }}</h2></div>
                            <div class="col-xs-6 col-sm-6 col-md-6"><h3 class="publisher">{{ console.publisher }}</h3></div>
                            <div class="col-xs-2 col-sm-2 col-md-2">
                            <!-- Update Console -->
                                <form action="{% url 'games:console_update' console.id %}" method="get" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="game_id" value="{{ game.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                </form>
                             </div>
                            <div class="col-xs-2 col-sm-2 col-md-2">
                            <!-- Delete Console -->
                                <form action="{% url 'games:console_delete' console.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="game_id" value="{{ game.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                            </div>

                        </div>
                    </div>


                </div>
</div>

            </a>
        </div>

        {% endfor %}
      </div>

    </div>

    {% else %}

    <h3>No consoles to list...</h3>

    {% endif %}

{% endblock %}

games/templates/games/registration_form.html
{% extends 'games/base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'games/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>


{% endblock %}